"accelerate_launch_args":
  use_fsdp: true
  fsdp_auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: "HYBRID_SHARD"
  fsdp_state_dict_type: "SHARDED_STATE_DICT"
  fsdp_cpu_ram_efficient_loading: true
  fsdp_sync_module_states: true